/* global use, db */
// MongoDB Playground
// Use Ctrl+Space inside a snippet or a string literal to trigger completions.

// The current database to use.
use("EliteShoppe");


db.getCollection('product').insertMany([
  { 'item': 'Cosmetics', 'category': 'Cosmetics', 'price': 100, 'brand': "tusker", 'model': "Elite Premium", 'quantity': 2, 'date': new Date() },
  { 'item': 'Cosmetics2', 'category': 'Cosmetics', 'price': 200, 'brand': "tusker", 'model': "Elite Premium", 'date': new  Date()  },
  { 'item': 'Cosmetics3', 'category': 'Cosmetics', 'price': 50, 'brand': "tusker", 'model': "Elite Premium", 'date': new Date()  },
  { 'item': 'Cosmetics4', 'category': 'Cosmetics', 'price': 50, 'brand': "tusker", 'model': "Elite Premium", 'date': new Date() },
  { 'item': 'Cosmetics5', 'category': 'Cosmetics', 'price': 100, 'brand': "tusker", 'model': "Elite Premium",'date': new Date() },
  { 'item': 'Cosmetics6', 'category': 'Cosmetics', 'price': 750, 'brand': "tusker", 'model': "Elite Premium", 'date': new Date() },
  { 'item': 'Cosmetics7', 'category': 'Cosmetics', 'price': 100, 'brand': "tusker", 'model': "Elite Premium",'date': new Date() },
  { 'item': 'Cosmetics8', 'category': 'Cosmetics', 'price': 750, 'brand': "tusker", 'model': "Elite Premium", 'date': new Date() },
  { 'item': 'Cosmetics9', 'category': 'Cosmetics', 'price': 759, 'brand': "tusker", 'model': "Elite Premium",  'date': new Date() },
  { 'item': 'Cosmetics10', 'category': 'Cosmetics', 'price': 1099, 'brand': "tusker", 'model': "Elite Premium", 'date': new Date() },
  { 'item': 'Cosmetics11', 'category': 'Cosmetics', 'price': 100, 'brand': "tusker", 'model': "Elite Premium", 'quantity': 2, 'date': new Date() },
  { 'item': 'Cosmetics12', 'category': 'Cosmetics', 'price': 200, 'brand': "tusker", 'model': "Elite Premium", 'date': new  Date()  },
  { 'item': 'Cosmetics13', 'category': 'Cosmetics', 'price': 50, 'brand': "tusker", 'model': "Elite Premium", 'date': new Date()  },
  { 'item': 'Cosmetics14', 'category': 'Cosmetics', 'price': 50, 'brand': "tusker", 'model': "Elite Premium", 'date': new Date() },
  { 'item': 'Cosmetics15', 'category': 'Cosmetics', 'price': 100, 'brand': "tusker", 'model': "Elite Premium",'date': new Date() },
  { 'item': 'Cosmetics16', 'category': 'Cosmetics', 'price': 100, 'brand': "tusker", 'model': "Elite Premium", 'quantity': 2, 'date': new Date() },
  { 'item': 'Cosmetics17', 'category': 'Cosmetics', 'price': 200, 'brand': "tusker", 'model': "Elite Premium", 'date': new  Date()  },
  { 'item': 'Cosmetics18', 'category': 'Cosmetics', 'price': 50, 'brand': "tusker", 'model': "Elite Premium", 'date': new Date()  },
  { 'item': 'Cosmetics19', 'category': 'Cosmetics', 'price': 50, 'brand': "tusker", 'model': "Elite Premium", 'date': new Date() },
  { 'item': 'Cosmetics20', 'category': 'Cosmetics', 'price': 100, 'brand': "tusker", 'model': "Elite Premium",'date': new Date() },
  { 'item': 'Cosmetics21', 'category': 'Cosmetics', 'price': 750, 'brand': "tusker", 'model': "Elite Premium", 'date': new Date() },
  { 'item': 'Cosmetics22', 'category': 'Cosmetics', 'price': 1099, 'brand': "tusker", 'model': "Elite Premium", 'date': new Date() },
]);

db.getCollection('product').insertMany([
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 100, 'brand': "tusker", 'model': "Elite Premium", 'quantity': 2, 'date': new Date() },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 200, 'brand': "tusker", 'model': "Elite Premium", 'date': new  Date()  },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 50, 'brand': "tusker", 'model': "Elite Premium", 'date': new Date()  },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 50, 'brand': "tusker", 'model': "Elite Premium", 'date': new Date() },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 100, 'brand': "tusker", 'model': "Elite Premium",'date': new Date() },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 750, 'brand': "tusker", 'model': "Elite Premium", 'date': new Date() },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 759, 'brand': "tusker", 'model': "Elite Premium",  'date': new Date() },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 1099, 'brand': "tusker", 'model': "Elite Premium", 'date': new Date() },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 100, 'brand': "tusker", 'model': "Elite Premium", 'quantity': 2, 'date': new Date() },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 200, 'brand': "tusker", 'model': "Elite Premium", 'date': new  Date()  },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 100, 'brand': "tusker", 'model': "Elite Premium", 'quantity': 2, 'date': new Date() },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 100, 'brand': "tusker", 'model': "Elite Premium", 'quantity': 2, 'date': new Date() },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 200, 'brand': "tusker", 'model': "Elite Premium", 'date': new  Date()  },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 50, 'brand': "tusker", 'model': "Elite Premium", 'date': new Date()  },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 50, 'brand': "tusker", 'model': "Elite Premium", 'date': new Date() },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 100, 'brand': "tusker", 'model': "Elite Premium",'date': new Date() },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 750, 'brand': "tusker", 'model': "Elite Premium", 'date': new Date() },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 759, 'brand': "tusker", 'model': "Elite Premium",  'date': new Date() },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 1099, 'brand': "tusker", 'model': "Elite Premium", 'date': new Date() },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 100, 'brand': "tusker", 'model': "Elite Premium", 'quantity': 2, 'date': new Date() },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 200, 'brand': "tusker", 'model': "Elite Premium", 'date': new  Date()  },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 100, 'brand': "tusker", 'model': "Elite Premium", 'quantity': 2, 'date': new Date() },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 100, 'brand': "tusker", 'model': "Elite Premium", 'quantity': 2, 'date': new Date() },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 200, 'brand': "tusker", 'model': "Elite Premium", 'date': new  Date()  },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 50, 'brand': "tusker", 'model': "Elite Premium", 'date': new Date()  },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 50, 'brand': "tusker", 'model': "Elite Premium", 'date': new Date() },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 100, 'brand': "tusker", 'model': "Elite Premium",'date': new Date() },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 750, 'brand': "tusker", 'model': "Elite Premium", 'date': new Date() },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 759, 'brand': "tusker", 'model': "Elite Premium",  'date': new Date() },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 1099, 'brand': "tusker", 'model': "Elite Premium", 'date': new Date() },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 100, 'brand': "tusker", 'model': "Elite Premium", 'quantity': 2, 'date': new Date() },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 200, 'brand': "tusker", 'model': "Elite Premium", 'date': new  Date()  },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 100, 'brand': "tusker", 'model': "Elite Premium", 'quantity': 2, 'date': new Date() },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 100, 'brand': "tusker", 'model': "Elite Premium", 'quantity': 2, 'date': new Date() },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 200, 'brand': "tusker", 'model': "Elite Premium", 'date': new  Date()  },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 50, 'brand': "tusker", 'model': "Elite Premium", 'date': new Date()  },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 50, 'brand': "tusker", 'model': "Elite Premium", 'date': new Date() },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 100, 'brand': "tusker", 'model': "Elite Premium",'date': new Date() },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 750, 'brand': "tusker", 'model': "Elite Premium", 'date': new Date() },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 759, 'brand': "tusker", 'model': "Elite Premium",  'date': new Date() },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 1099, 'brand': "tusker", 'model': "Elite Premium", 'date': new Date() },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 100, 'brand': "tusker", 'model': "Elite Premium", 'quantity': 2, 'date': new Date() },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 200, 'brand': "tusker", 'model': "Elite Premium", 'date': new  Date()  },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 100, 'brand': "tusker", 'model': "Elite Premium", 'quantity': 2, 'date': new Date() },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 100, 'brand': "tusker", 'model': "Elite Premium", 'quantity': 2, 'date': new Date() },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 200, 'brand': "tusker", 'model': "Elite Premium", 'date': new  Date()  },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 50, 'brand': "tusker", 'model': "Elite Premium", 'date': new Date()  },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 50, 'brand': "tusker", 'model': "Elite Premium", 'date': new Date() },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 100, 'brand': "tusker", 'model': "Elite Premium",'date': new Date() },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 750, 'brand': "tusker", 'model': "Elite Premium", 'date': new Date() },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 759, 'brand': "tusker", 'model': "Elite Premium",  'date': new Date() },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 1099, 'brand': "tusker", 'model': "Elite Premium", 'date': new Date() },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 100, 'brand': "tusker", 'model': "Elite Premium", 'quantity': 2, 'date': new Date() },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 200, 'brand': "tusker", 'model': "Elite Premium", 'date': new  Date()  },
  { 'item': 'Hand Bag', 'category': 'Hand Bag', 'price': 100, 'brand': "tusker", 'model': "Elite Premium", 'quantity': 2, 'date': new Date() },
  
  
]);
